import os, math,sys
import ROOT
import copy
from optparse import OptionParser
from argparse import ArgumentParser
ROOT.gROOT.SetBatch(True)


parser = ArgumentParser()
parser.add_argument('-y','--year', dest='year', action='store', type=str,default='UL2018')
args = parser.parse_args()
year = args.year
 
samplelist = {'UL2018':
              ["SingleMuon_Run2018A-UL2018_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2018B-UL2018_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2018C-UL2018_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1",
              "EGamma_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1",
              "EGamma_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1",
              "EGamma_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1",
              "EGamma_Run2018D-UL2018_MiniAODv2_NanoAODv9-v3",
              #"SingleMuon_Run2018A-UL2018_HPS",
              #"SingleMuon_Run2018BCD-UL2018_HPS",
              #"SingleMuon_Run2018RECOV-UL2018_HPS",
              #"EGamma_Run2018A-UL2018_HPS",
              #"EGamma_Run2018BCD-UL2018_HPS",
              #"EGamma_Run2018RECOV-UL2018_HPS",
              #"MET_Run2018A-UL2018_MiniAODv2_NanoAODv9-v2",
              #"MET_Run2018B-UL2018_MiniAODv2_NanoAODv9-v2",
              #"MET_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1",
              #"TauEmbedding_data_2018_MuTau_nanoaod_Run2018A",
              #"TauEmbedding_data_2018_MuTau_nanoaod_Run2018B",
              #"TauEmbedding_data_2018_MuTau_nanoaod_Run2018C",
              #"TauEmbedding_data_2018_MuTau_nanoaod_Run2018D",
              #"TauEmbedding_data_2018_ElTau_nanoaod_Run2018A",
              #"TauEmbedding_data_2018_ElTau_nanoaod_Run2018B",
              #"TauEmbedding_data_2018_ElTau_nanoaod_Run2018C",
              #"TauEmbedding_data_2018_ElTau_nanoaod_Run2018D",
              #"DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "TTToHadronic_TuneCP5_13TeV-powheg-pythia8",
              "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8",
              "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8",
              "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8", 
              "GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8",
              "ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1",
              "WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo4L_TuneCP5_13TeV_powheg_pythia8",
              "ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8", 
              #"ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8",
              "DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              #"DYJetsToMuMu_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos",
              #"DYJetsToEE_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos",
              #"DYJetsToTauTau_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos",
              "WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_HPS",
              ],
              'UL2017':
              ["SingleMuon_Run2017B-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2017C-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2017D-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2017E-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2017F-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2017B-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2017C-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2017D-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2017E-UL2017_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2017F-UL2017_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2017B-UL2017_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2017C-UL2017_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2017D-UL2017_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2017E-UL2017_MiniAODv2_NanoAODv9-v1",
              #"MET_Run2017F-UL2017_MiniAODv2_NanoAODv9-v1",
              "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "TTToHadronic_TuneCP5_13TeV-powheg-pythia8",
              "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8",
              "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8",
              "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8", 
              "GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8",
              "ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1",
              "WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo4L_TuneCP5_13TeV_powheg_pythia8",
              "ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              #"ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8",
              #"DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              "DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"SUSYGluGluToBBHToTauTau_M-80_TuneCP5_13TeV-amcatnlo-pythia8", 
              #"SUSYGluGluToBBHToTauTau_M-90_TuneCP5_13TeV-amcatnlo-pythia8",
              #"SUSYGluGluToBBHToTauTau_M-110_TuneCP5_13TeV-amcatnlo-pythia8",
              #"SUSYGluGluToBBHToTauTau_M-120_TuneCP5_13TeV-amcatnlo-pythia8", 
              #"SUSYGluGluToBBHToTauTau_M-125_TuneCP5_13TeV-amcatnlo-pythia8", 
              #"SUSYGluGluToBBHToTauTau_M-130_TuneCP5_13TeV-amcatnlo-pythia8",  
              #"SUSYGluGluToBBHToTauTau_M-140_TuneCP5_13TeV-amcatnlo-pythia8",  
              #"SUSYGluGluToBBHToTauTau_M-160_TuneCP5_13TeV-amcatnlo-pythia8",   
              #"SUSYGluGluToBBHToTauTau_M-180_TuneCP5_13TeV-amcatnlo-pythia8",  
              #"SUSYGluGluToBBHToTauTau_M-200_TuneCP5_13TeV-amcatnlo-pythia8",  
              #"SUSYGluGluToBBHToTauTau_M-250_TuneCP5_13TeV-amcatnlo-pythia8",
              #"SUSYGluGluToBBHToTauTau_M-300_TuneCP5_13TeV-amcatnlo-pythia8",
                ],
              'UL2016':
              ["SingleMuon_Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleMuon_Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2016F-UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2016G-UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleMuon_Run2016H-UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleElectron_Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleElectron_Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleElectron_Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2",
              "SingleElectron_Run2016F-UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2016G-UL2016_MiniAODv2_NanoAODv9-v1",
              "SingleElectron_Run2016H-UL2016_MiniAODv2_NanoAODv9-v1",
              #"DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "TTToHadronic_TuneCP5_13TeV-powheg-pythia8",
              "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8",
              "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8",
              "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8", 
              "GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8",
              "ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1",
              "WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo4L_TuneCP5_13TeV_powheg_pythia8",
              "ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              #"ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8",
              "DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              ],
              'UL2016_preVFP':
              [#"DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              #"W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
              "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "TTToHadronic_TuneCP5_13TeV-powheg-pythia8",
              "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8",
              "ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8",
              "ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8",
              "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8",
              "GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8", 
              "GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8",
              "VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              #"ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8",
              #"tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8",
              "ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1",
              "WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8",
              "WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo4L_TuneCP5_13TeV_powheg_pythia8",
              "ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              #"ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8",
              "DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8",
              "WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              "WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8",
              ],
}


pre_path = '/pnfs/psi.ch/cms/trivcat/store/user/pbaertsc/bbh'

outputdir = "sampleslist/%s"%year

for sample in samplelist[year]:
    files = []
    multi_dir = False
    if sample.split("_")[0] in ["Tau","MuonEG","SingleElectron","EGamma","SingleMuon","MET"]:
        path ="%s/%s/%s__%s"%(pre_path,sample.split("_")[0],sample,year)
    elif "_ext" in sample and year=="2018":
        path = "%s/%s/%s__%s"%(pre_path,sample[:-5],sample,year)
    #elif "SUSY" in sample:
    #   path = "%s/%s/%s__2018"%(pre_path,sample,sample) 
    elif "HPS" in sample:
        path = "%s/%s/%s__%s"%(pre_path,sample[:-4],sample,year)
    elif "Embedding" in sample:
        path = "%s/TauEmbedding/%s"%(pre_path,sample)
    else: 
        path = "%s/%s/%s__%s"%(pre_path,sample,sample,year)
    if os.path.isdir(path)==False:
        print(sample,"doesn't exist")
        continue
    if len([i for i in os.listdir(path)])>1:
        print("WARNING: more than 1 directory found for",sample,"!")
        multi_dir = True
    for root, dirs, fs in os.walk(path):
        if multi_dir and 'log' in dirs:
            if root.split("/")[-2][1]!="3":
                continue
        for f in fs:
            if '.root' in f:
                #print(pre_path+ os.path.join(root,f))
                files.append(os.path.join(root,f))
    with open(os.path.join(outputdir,sample)+".txt",'w') as out:
        for f in files:
            out.write("{}\n".format(f))

print("done")
        
