

def getsamples(channel,year,preVFP):
    data_dict = data_samples["UL%s%s"%(year,preVFP)][channel]
    mc_dict = samples["UL%s"%year] #preVFP not used because samples the same for preVFP and postVFP
    data_dict.update(mc_dict)
    return data_dict

def getMCsamples(year):
    return samples["UL%s"%year] 
"""
'UL2018':{
        'mutau':{'data_obs': 'SingleMuon_Run2018ABCD',
                 'TauEmbedding': 'TauEmbedding_MuTau_Run2018ABCD'},
        'etau': {'data_obs': 'EGamma_Run2018ABCD',
                 'TauEmbedding': 'TauEmbedding_ElTau_Run2018ABCD'},
        'mumu': {'data_obs': 'SingleMuon_Run2018ABCD',
                 'TauEmbedding': 'TauEmbedding_MuTau_Run2018ABCD'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2018ABCD',
                 'TauEmbedding': 'TauEmbedding_MuTau_Run2018ABCD'},
    },
"""

data_samples = {
    'UL2018':{
        'mutau':{'data_obs': 'SingleMuon_Run2018ABCD'},
        'etau': {'data_obs': 'EGamma_Run2018ABCD'},
        'mumu': {'data_obs': 'SingleMuon_Run2018ABCD'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2018ABCD'},
    },
    'UL2017':{
        'mutau':{'data_obs': 'SingleMuon_Run2017BCDEF'},
        'etau': {'data_obs': 'SingleElectron_Run2017BCDEF'},
        'mumu': {'data_obs': 'SingleMuon_Run2017BCDEF'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2017BCDEF'},
    },
    'UL2016_comb':{
        'mutau':{'data_obs': 'SingleMuon_Run2016BCDEFGH'},
        'etau': {'data_obs': 'SingleElectron_Run2016BCDEFGH'},
        'mumu': {'data_obs': 'SingleMuon_Run2016BCDEFGH'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2016BCDEFGH'},
    },
    'UL2016_preVFP':{
        'mutau':{'data_obs': 'SingleMuon_Run2016BCDEF'},
        'etau': {'data_obs': 'SingleElectron_Run2016BCDEF'},
        'mumu': {'data_obs': 'SingleMuon_Run2016BCDEF'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2016BCDEF'},
    },
    'UL2016':{
        'mutau':{'data_obs': 'SingleMuon_Run2016FGH'},
        'etau': {'data_obs': 'SingleElectron_Run2016FGH',},
        'mumu': {'data_obs': 'SingleMuon_Run2016FGH'},
        'tt':   {'data_obs': 'SingleMuon_SingleElectron_Run2016FGH'},
    },
}


samples = {
    'UL2018':{
        #'WJets_LOincl': 'WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W1Jets': 'W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W2Jets': 'W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W3Jets': 'W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W4Jets': 'W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'DYJets_LOincl':'DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY1Jets':'DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY2Jets':'DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY3Jets':'DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY4Jets':'DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        'WJets_incl': 'WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_0J': 'WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_1J': 'WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',  
        'WJets_2J': 'WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_incl':'DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_0J':'DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_1J':'DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_2J':'DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        #'DYJetsToMuMu':'DYJetsToMuMu_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos',
        #'DYJetsToEE':'DYJetsToEE_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos',
        #'DYJetsToTauTau':'DYJetsToTauTau_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos',
        #'DYJets_faketaus': 'DYJetsToLL_faketaus',
        'TTTo2L2Nu':'TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'TTToHadronic':'TTToHadronic_TuneCP5_13TeV-powheg-pythia8',
        'TTToSemiLeptonic':'TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8',
        'ST_t_channel_antitop': 'ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_t_channel_top': 'ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_s_channel':'ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8',
        'ST_tW_antitop':'ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'ST_tW_top':'ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'VBF':'VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ttH':'ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ZH':'ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1',
        'WplusH':'WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WminusH':'WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WWTo2L2Nu':'WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'WWTo1L1Nu2Q':'WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WWTo4Q':'WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo3LNu':'WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo2L2Q':'WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L3Nu':'WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L1Nu2Q':'WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo4L':'ZZTo4L_TuneCP5_13TeV_powheg_pythia8',
        'ZZTo2L2Q':'ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo2Nu2Q':'ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        #'ZZTo2L2Nu':'ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8',
        #'ttZJets':'ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'ttWJets':'ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'tZq':'tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8',
        'bbH_htt': 'bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_excl': 'bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_inc': 'GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_bb_htt': 'bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
        'bbH_nobb_htt': 'jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_htt_excl': 'jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_htt_inc': 'GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_htt': 'jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
    },
    'UL2017':{
        #'WJets_LOincl': 'WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W1Jets': 'W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W2Jets': 'W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W3Jets': 'W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W4Jets': 'W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'DYJets_LOincl':'DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY1Jets':'DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY2Jets':'DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY3Jets':'DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY4Jets':'DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        'WJets_incl': 'WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_0J': 'WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_1J': 'WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',  
        'WJets_2J': 'WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_incl':'DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_0J':'DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_1J':'DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_2J':'DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'TTTo2L2Nu':'TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'TTToHadronic':'TTToHadronic_TuneCP5_13TeV-powheg-pythia8',
        'TTToSemiLeptonic':'TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8',
        'ST_t_channel_antitop': 'ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_t_channel_top': 'ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_s_channel':'ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8',
        'ST_tW_antitop':'ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'ST_tW_top':'ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'VBF':'VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ttH':'ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ZH':'ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1',
        'WplusH':'WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WminusH':'WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WWTo2L2Nu':'WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'WWTo1L1Nu2Q':'WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WWTo4Q':'WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo3LNu':'WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo2L2Q':'WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L3Nu':'WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L1Nu2Q': 'WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo4L':'ZZTo4L_TuneCP5_13TeV_powheg_pythia8',
        'ZZTo2L2Q':'ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo2Nu2Q':'ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        #'ZZTo2L2Nu':'ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8',
        #'ttZJets':'ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'ttWJets':'ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'tZq':'tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8',
        'bbH_htt': 'bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_excl': 'bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_inc': 'GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_bb_htt': 'bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
        'bbH_nobb_htt': 'jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_htt_excl': 'jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_htt_inc': 'GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_htt': 'jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
    },
    'UL2016':{
        #'WJets_LOincl': 'WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W1Jets': 'W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W2Jets': 'W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'W3Jets': 'W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'W4Jets': 'W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8',  
        #'DYJets_LOincl':'DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY1Jets':'DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY2Jets':'DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY3Jets':'DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        #'DY4Jets':'DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8',
        'WJets_incl': 'WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_0J': 'WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WJets_1J': 'WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',  
        'WJets_2J': 'WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_incl':'DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_0J':'DYJetsToLL_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_1J':'DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'DYJets_2J':'DYJetsToLL_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'TTTo2L2Nu':'TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'TTToHadronic':'TTToHadronic_TuneCP5_13TeV-powheg-pythia8',
        'TTToSemiLeptonic':'TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8',
        'ST_t_channel_antitop': 'ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_t_channel_top': 'ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8',
        'ST_s_channel':'ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8',
        'ST_tW_antitop':'ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'ST_tW_top':'ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8',
        'VBF':'VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ttH':'ttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'ZH':'ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1',
        'WplusH':'WplusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WminusH':'WminusHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8',
        'WWTo2L2Nu':'WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8',
        'WWTo1L1Nu2Q':'WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WWTo4Q':'WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo3LNu':'WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo2L2Q':'WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L3Nu':'WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'WZTo1L1Nu2Q':'WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo4L':'ZZTo4L_TuneCP5_13TeV_powheg_pythia8',
        'ZZTo2L2Q':'ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'ZZTo2Nu2Q':'ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        #'ZZTo2L2Nu':'ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8',
        #'ttZJets':'ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'ttWJets':'ttWJets_TuneCP5_13TeV_madgraphMLM_pythia8',
        #'tZq':'tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8',
        'bbH_htt': 'bbHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_excl': 'bbHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_bb_htt_inc': 'GluGluHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_bb_htt': 'bbHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
        'bbH_nobb_htt': 'jjHToTauTau_M-125_4FS_TuneCP5_yb2_13TeV-amcatnlo-pythia8',
        'ggH_htt_excl': 'jjHToTauTau_M-125_4FS_TuneCP5_yt2_13TeV-amcatnlo-pythia8',
        'ggH_htt_inc': 'GluGlujjHToTauTau_M-125_TuneCP5_13TeV-amcatnloFXFX-pythia8',
        'intH_htt': 'jjHToTauTau_M-125_4FS_ybyt_TuneCP5-13TeV-amcatnlo-pythia8',
    }
}

