import plotting as plot
from analysis import *
import ROOT
import argparse
import json
import os
import fnmatch
from copy import deepcopy
from array import array
import numpy as np
from ROOT import gStyle,TCanvas,TH1D,TH2D, TLatex
ROOT.gROOT.SetBatch(ROOT.kTRUE)

parser = argparse.ArgumentParser()
parser.add_argument('--input', '-i', help='File with histograms to plot')
parser.add_argument('--output', '-o', default='./plots', help='top level output directory')
args = parser.parse_args()

filename = args.input
file = ROOT.TFile("root/"+filename)

node = TDirToNode(file)

made_dirs = set()
year = filename.split("_")[1].split(".")[0]
if "preVFP" in filename:
  year=year+"_preVFP"
elif "comb" in filename:
  year=year+"_comb"
channel=filename.split("_")[0]

if year=="UL2018":
  lumi = 59.7
elif year=="UL2017":
  lumi = 41.5
elif year=="UL2016":
  lumi = 36.3

titleright = "%s %.1f fb^{-1} (13 TeV)"%(year[2:],float(lumi))

outfile = ROOT.TFile('root/MCCorr_%s_%s.root'%(channel,year), 'RECREATE')

hists_taupt = {}
hists_pt = {}
hists_mass = {}
hists = {}
hists_pt_1btag = {}
hists_mass_1btag = {}
hists_1btag = {}
hists_pt_2btag = {}
hists_mass_2btag = {}
hists_2btag = {}

for path, subnode in node.ListNodes(withObjects=True):
  if path not in ["vis_pt","vis_mass","2D","vis_pt_1btag","vis_mass_1btag","2D_1btag","vis_pt_2btag","vis_mass_2btag","2D_2btag","Tau1_pt"]:
    continue
  split_path = path.split('/')[:-1]
  name = path.split('/')[-1]
  for opath,objname, obj in subnode.ListObjects(depth=0):
    if path=="vis_pt":
      hists_pt[objname] = obj
    elif path=="vis_mass":
      hists_mass[objname] = obj
    elif path=="2D":
      hists[objname]=obj
    elif path=="vis_pt_1btag":
      hists_pt_1btag[objname] = obj
    elif path=="vis_mass_1btag":
      hists_mass_1btag[objname] = obj
    elif path=="2D_1btag":
      hists_1btag[objname]=obj
    elif path=="vis_pt_2btag":
      hists_pt_2btag[objname] = obj
    elif path=="vis_mass_2btag":
      hists_mass_2btag[objname] = obj
    elif path=="2D_2btag":
      hists_2btag[objname]=obj
    elif path=="Tau1_pt":
      hists_taupt[objname] = obj

if channel=="mumu":
  channel_text = "#mu#mu CR"
  canv4 = TCanvas("DYJetscorr_NLO","DYJets MC Correction NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO = TH2D("DYJetscorr_NLO","DYJets Correction NLO",20,0.,200.,16,50.,130.)
  DYJets_corr_NLO.Divide(hists["data_obs"],hists["DYJets_incl"])
  DYJets_corr_NLO.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO.GetNbinsY()+2):
      if DYJets_corr_NLO.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO.Draw("COLZ")
  #plot.DrawCMSLogo(canv4, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv4, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv4, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv4.SaveAs("plots/%s_%s/DYJetscorr_NLO.pdf"%(channel,year))
  canv4.SaveAs("plots/%s_%s/DYJetscorr_NLO.png"%(channel,year))
  DYJets_corr_NLO.Write()
  canv5 = TCanvas("DYJetscorr_pt_NLO","DYJets Correction pt NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO = TH1D("DYJetscorr_pt_NLO","DYJets Correction pt NLO",20,0.,200.)
  DYJets_corr_pt_NLO.Divide(hists_pt["dataMinusMC"],hists_pt["DYJets"])
  DYJets_corr_pt_NLO.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO.Draw()
  #plot.DrawCMSLogo(canv5, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv5, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv5, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv5.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO.pdf"%(channel,year))
  canv5.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO.png"%(channel,year))
  canv6 = TCanvas("DYJetscorr_mass_NLO","DYJets Correction mass NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO = TH1D("DYJetscorr_mass_NLO","DYJets Correction mass NLO",16,50.,130.)
  DYJets_corr_mass_NLO.Divide(hists_mass["dataMinusMC"],hists_mass["DYJets"])
  DYJets_corr_mass_NLO.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO.Draw()
  #plot.DrawCMSLogo(canv6, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv6, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv6, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv6.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO.pdf"%(channel,year))
  canv6.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO.png"%(channel,year))
  #NLO 1btag
  canv10 = TCanvas("DYJetscorr_NLO_1btag","DYJets MC Correction NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  #DYJets_corr_NLO_1btag = TH2D("DYJetscorr_NLO_1btag","DYJets Correction NLO 1btag",20,0.,200.,16,50.,130.)
  DYJets_corr_NLO_1btag = TH2D("DYJetscorr_NLO_1btag","",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_1btag.Divide(hists_1btag["data_obs"],hists_1btag["DYJets_incl"])
  DYJets_corr_NLO_1btag.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_1btag.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_1btag.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_1btag.GetNbinsY()+2):
      if DYJets_corr_NLO_1btag.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_1btag.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_1btag.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_1btag.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_1btag.Draw("COLZ")
  #plot.DrawCMSLogo(canv10, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv10, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv10, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 1 b-jet")
  canv10.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag.pdf"%(channel,year))
  canv10.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag.png"%(channel,year))
  canv10.SaveAs("plots/thesis/DYJetscorr_NLO_1btag_%s_%s.pdf"%(channel,year))
  DYJets_corr_NLO_1btag.Write()
  canv11 = TCanvas("DYJetscorr_pt_NLO_1btag","DYJets Correction pt NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_1btag = TH1D("DYJetscorr_pt_NLO_1btag","DYJets Correction pt NLO 1btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_1btag.Divide(hists_pt_1btag["dataMinusMC"],hists_pt_1btag["DYJets"])
  DYJets_corr_pt_NLO_1btag.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_1btag.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_1btag.Draw()
  #plot.DrawCMSLogo(canv11, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv11, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv11, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 1 b-jet")
  canv11.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag.pdf"%(channel,year))
  canv11.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag.png"%(channel,year))
  canv12 = TCanvas("DYJetscorr_mass_NLO_1btag","DYJets Correction mass NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_1btag = TH1D("DYJetscorr_mass_NLO_1btag","DYJets Correction mass NLO 1btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_1btag.Divide(hists_mass_1btag["dataMinusMC"],hists_mass_1btag["DYJets"])
  DYJets_corr_mass_NLO_1btag.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_1btag.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_1btag.Draw()
  #plot.DrawCMSLogo(canv12, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv12, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv12, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 1 b-jet")
  canv12.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag.pdf"%(channel,year))
  canv12.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag.png"%(channel,year))
  #NLO 2btag
  canv16 = TCanvas("DYJetscorr_NLO_2btag","DYJets MC Correction NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  #DYJets_corr_NLO_2btag = TH2D("DYJetscorr_NLO_2btag","DYJets Correction NLO 2btag",20,0.,200.,16,50.,130.)
  DYJets_corr_NLO_2btag = TH2D("DYJetscorr_NLO_2btag","",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_2btag.Divide(hists_2btag["data_obs"],hists_2btag["DYJets_incl"])
  DYJets_corr_NLO_2btag.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_2btag.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_2btag.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_2btag.GetNbinsY()+2):
      if DYJets_corr_NLO_2btag.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_2btag.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_2btag.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_2btag.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_2btag.Draw("COLZ")
  #plot.DrawCMSLogo(canv16, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv16, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv16, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 2 b-jets")
  canv16.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag.pdf"%(channel,year))
  canv16.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag.png"%(channel,year))
  canv16.SaveAs("plots/thesis/DYJetscorr_NLO_2btag_%s_%s.pdf"%(channel,year))
  DYJets_corr_NLO_2btag.Write()
  canv17 = TCanvas("DYJetscorr_pt_NLO_2btag","DYJets Correction pt NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_2btag = TH1D("DYJetscorr_pt_NLO_2btag","DYJets Correction pt NLO 2btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_2btag.Divide(hists_pt_2btag["dataMinusMC"],hists_pt_2btag["DYJets"])
  DYJets_corr_pt_NLO_2btag.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_2btag.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_2btag.Draw()
  #plot.DrawCMSLogo(canv17, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv17, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv17, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 2 b-jets")
  canv17.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag.pdf"%(channel,year))
  canv17.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag.png"%(channel,year))
  canv18 = TCanvas("DYJetscorr_mass_NLO_2btag","DYJets Correction mass NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_2btag = TH1D("DYJetscorr_mass_NLO_2btag","DYJets Correction mass NLO 2btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_2btag.Divide(hists_mass_2btag["dataMinusMC"],hists_mass_2btag["DYJets"])
  DYJets_corr_mass_NLO_2btag.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_2btag.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_2btag.Draw()
  #plot.DrawCMSLogo(canv18, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv18, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv18, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", 2 b-jets")
  canv18.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag.pdf"%(channel,year))
  canv18.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag.png"%(channel,year))

  #NLO up
  canv19 = TCanvas("DYJetscorr_NLO_up","DYJets MC Correction NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_up = TH2D("DYJetscorr_NLO_up","DYJets Correction NLO",20,0.,200.,16,50.,130.)
  DYJets_corr_NLO_up.Divide(hists["data_obs_up"],hists["DYJets_incl"])
  DYJets_corr_NLO_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_up.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_up.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_up.GetNbinsY()+2):
      if DYJets_corr_NLO_up.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_up.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_up.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_up.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_up.Draw("COLZ")
  #plot.DrawCMSLogo(canv19, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv19, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv19, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv19.SaveAs("plots/%s_%s/DYJetscorr_NLO_up.pdf"%(channel,year))
  canv19.SaveAs("plots/%s_%s/DYJetscorr_NLO_up.png"%(channel,year))
  DYJets_corr_NLO_up.Write()
  canv20 = TCanvas("DYJetscorr_pt_NLO_up","DYJets Correction pt NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_up = TH1D("DYJetscorr_pt_NLO_up","DYJets Correction pt NLO",20,0.,200.)
  DYJets_corr_pt_NLO_up.Divide(hists_pt["dataMinusMC_up"],hists_pt["DYJets"])
  DYJets_corr_pt_NLO_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_up.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_up.Draw()
  #plot.DrawCMSLogo(canv20, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv20, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv20, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv20.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_up.pdf"%(channel,year))
  canv20.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_up.png"%(channel,year))
  canv21 = TCanvas("DYJetscorr_mass_NLO_up","DYJets Correction mass NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_up = TH1D("DYJetscorr_mass_NLO_up","DYJets Correction mass NLO",16,50.,130.)
  DYJets_corr_mass_NLO_up.Divide(hists_mass["dataMinusMC_up"],hists_mass["DYJets"])
  DYJets_corr_mass_NLO_up.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_up.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_up.Draw()
  #plot.DrawCMSLogo(canv21, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv21, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv21, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv21.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_up.pdf"%(channel,year))
  canv21.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_up.png"%(channel,year))


  #NLO 1btag up
  canv22 = TCanvas("DYJetscorr_NLO_1btag_up","DYJets MC Correction NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_1btag_up = TH2D("DYJetscorr_NLO_1btag_up","DYJets Correction NLO 1btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_1btag_up.Divide(hists_1btag["data_obs_up"],hists_1btag["DYJets_incl"])
  DYJets_corr_NLO_1btag_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_1btag_up.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_1btag_up.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_1btag_up.GetNbinsY()+2):
      if DYJets_corr_NLO_1btag_up.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_1btag_up.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_1btag_up.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_1btag_up.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_1btag_up.Draw("COLZ")
  #plot.DrawCMSLogo(canv22, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv22, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv22, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv22.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag_up.pdf"%(channel,year))
  canv22.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag_up.png"%(channel,year))
  DYJets_corr_NLO_1btag_up.Write()
  canv23 = TCanvas("DYJetscorr_pt_NLO_1btag_up","DYJets Correction pt NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_1btag_up = TH1D("DYJetscorr_pt_NLO_1btag_up","DYJets Correction pt NLO 1btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_1btag_up.Divide(hists_pt_1btag["dataMinusMC_up"],hists_pt_1btag["DYJets"])
  DYJets_corr_pt_NLO_1btag_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_1btag_up.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_1btag_up.Draw()
  #plot.DrawCMSLogo(canv23, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv23, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv23, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv23.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag_up.pdf"%(channel,year))
  canv23.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag_up.png"%(channel,year))
  canv24 = TCanvas("DYJetscorr_mass_NLO_1btag_up","DYJets Correction mass NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_1btag_up = TH1D("DYJetscorr_mass_NLO_1btag_up","DYJets Correction mass NLO 1btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_1btag_up.Divide(hists_mass_1btag["dataMinusMC_up"],hists_mass_1btag["DYJets"])
  DYJets_corr_mass_NLO_1btag_up.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_1btag_up.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_1btag_up.Draw()
  #plot.DrawCMSLogo(canv24, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv24, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv24, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv24.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag_up.pdf"%(channel,year))
  canv24.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag_up.png"%(channel,year))
  #NLO 2btag up
  canv25 = TCanvas("DYJetscorr_NLO_2btag_up","DYJets MC Correction NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_2btag_up = TH2D("DYJetscorr_NLO_2btag_up","DYJets Correction NLO 2btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_2btag_up.Divide(hists_2btag["data_obs_up"],hists_2btag["DYJets_incl"])
  DYJets_corr_NLO_2btag_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_2btag_up.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_2btag_up.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_2btag_up.GetNbinsY()+2):
      if DYJets_corr_NLO_2btag_up.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_2btag_up.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_2btag_up.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_2btag_up.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_2btag_up.Draw("COLZ")
  #plot.DrawCMSLogo(canv25, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv25, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv25, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv25.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag_up.pdf"%(channel,year))
  canv25.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag_up.png"%(channel,year))
  DYJets_corr_NLO_2btag_up.Write()
  canv26 = TCanvas("DYJetscorr_pt_NLO_2btag_up","DYJets Correction pt NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_2btag_up = TH1D("DYJetscorr_pt_NLO_2btag_up","DYJets Correction pt NLO 2btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_2btag_up.Divide(hists_pt_2btag["dataMinusMC_up"],hists_pt_2btag["DYJets"])
  DYJets_corr_pt_NLO_2btag_up.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_2btag_up.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_2btag_up.Draw()
  #plot.DrawCMSLogo(canv26, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv26, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv26, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv26.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag_up.pdf"%(channel,year))
  canv26.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag_up.png"%(channel,year))
  canv27 = TCanvas("DYJetscorr_mass_NLO_2btag_up","DYJets Correction mass NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_2btag_up = TH1D("DYJetscorr_mass_NLO_2btag_up","DYJets Correction mass NLO 2btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_2btag_up.Divide(hists_mass_2btag["dataMinusMC_up"],hists_mass_2btag["DYJets"])
  DYJets_corr_mass_NLO_2btag_up.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_2btag_up.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_2btag_up.Draw()
  #plot.DrawCMSLogo(canv27, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv27, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv27,titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec up")
  canv27.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag_up.pdf"%(channel,year))
  canv27.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag_up.png"%(channel,year))

  #NLO down
  canv28 = TCanvas("DYJetscorr_NLO_down","DYJets MC Correction NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_down = TH2D("DYJetscorr_NLO_down","DYJets Correction NLO",20,0.,200.,16,50.,130.)
  DYJets_corr_NLO_down.Divide(hists["data_obs_down"],hists["DYJets_incl"])
  DYJets_corr_NLO_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_down.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_down.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_down.GetNbinsY()+2):
      if DYJets_corr_NLO_down.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_down.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_down.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_down.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_down.Draw("COLZ")
  #plot.DrawCMSLogo(canv28, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv28, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv28, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv28.SaveAs("plots/%s_%s/DYJetscorr_NLO_down.pdf"%(channel,year))
  canv28.SaveAs("plots/%s_%s/DYJetscorr_NLO_down.png"%(channel,year))
  DYJets_corr_NLO_down.Write()
  canv29 = TCanvas("DYJetscorr_pt_NLO_down","DYJets Correction pt NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_down = TH1D("DYJetscorr_pt_NLO_down","DYJets Correction pt NLO",20,0.,200.)
  DYJets_corr_pt_NLO_down.Divide(hists_pt["dataMinusMC_down"],hists_pt["DYJets"])
  DYJets_corr_pt_NLO_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_down.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_down.Draw()
  #plot.DrawCMSLogo(canv29, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv29, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv29, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv29.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_down.pdf"%(channel,year))
  canv29.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_down.png"%(channel,year))
  canv30 = TCanvas("DYJetscorr_mass_NLO_down","DYJets Correction mass NLO",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_down = TH1D("DYJetscorr_mass_NLO_down","DYJets Correction mass NLO",16,50.,130.)
  DYJets_corr_mass_NLO_down.Divide(hists_mass["dataMinusMC_down"],hists_mass["DYJets"])
  DYJets_corr_mass_NLO_down.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_down.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_down.Draw()
  #plot.DrawCMSLogo(canv30, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv30, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv30, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv30.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_down.pdf"%(channel,year))
  canv30.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_down.png"%(channel,year))

  #NLO 1btag down
  canv31 = TCanvas("DYJetscorr_NLO_1btag_down","DYJets MC Correction NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_1btag_down = TH2D("DYJetscorr_NLO_1btag_down","DYJets Correction NLO 1btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_1btag_down.Divide(hists_1btag["data_obs_down"],hists_1btag["DYJets_incl"])
  DYJets_corr_NLO_1btag_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_1btag_down.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_1btag_down.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_1btag_down.GetNbinsY()+2):
      if DYJets_corr_NLO_1btag_down.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_1btag_down.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_1btag_down.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_1btag_down.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_1btag_down.Draw("COLZ")
  #plot.DrawCMSLogo(canv31, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv31, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv31, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv31.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag_down.pdf"%(channel,year))
  canv31.SaveAs("plots/%s_%s/DYJetscorr_NLO_1btag_down.png"%(channel,year))
  DYJets_corr_NLO_1btag_down.Write()
  canv32 = TCanvas("DYJetscorr_pt_NLO_1btag_down","DYJets Correction pt NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_1btag_down = TH1D("DYJetscorr_pt_NLO_1btag_down","DYJets Correction pt NLO 1btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_1btag_down.Divide(hists_pt_1btag["dataMinusMC_down"],hists_pt_1btag["DYJets"])
  DYJets_corr_pt_NLO_1btag_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_1btag_down.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_1btag_down.Draw()
  #plot.DrawCMSLogo(canv32, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv32, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv32, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv32.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag_down.pdf"%(channel,year))
  canv32.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_1btag_down.png"%(channel,year))
  canv33 = TCanvas("DYJetscorr_mass_NLO_1btag_down","DYJets Correction mass NLO 1btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_1btag_down = TH1D("DYJetscorr_mass_NLO_1btag_down","DYJets Correction mass NLO 1btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_1btag_down.Divide(hists_mass_1btag["dataMinusMC_down"],hists_mass_1btag["DYJets"])
  DYJets_corr_mass_NLO_1btag_down.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_1btag_down.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_1btag_down.Draw()
  #plot.DrawCMSLogo(canv33, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv33, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv33, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv33.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag_down.pdf"%(channel,year))
  canv33.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_1btag_down.png"%(channel,year))
  #NLO 2btag down
  canv34 = TCanvas("DYJetscorr_NLO_2btag_down","DYJets MC Correction NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_NLO_2btag_down = TH2D("DYJetscorr_NLO_2btag_down","DYJets Correction NLO 2btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]),8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_NLO_2btag_down.Divide(hists_2btag["data_obs_down"],hists_2btag["DYJets_incl"])
  DYJets_corr_NLO_2btag_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_NLO_2btag_down.GetYaxis().SetTitle("dilepton mass (GeV)")
  for pt_bin in range(1,DYJets_corr_NLO_2btag_down.GetNbinsX()+2):
    for mass_bin in range(1,DYJets_corr_NLO_2btag_down.GetNbinsY()+2):
      if DYJets_corr_NLO_2btag_down.GetBinContent(pt_bin,mass_bin)>4.: DYJets_corr_NLO_2btag_down.SetBinContent(pt_bin,mass_bin,1.)
      if DYJets_corr_NLO_2btag_down.GetBinContent(pt_bin,mass_bin)<0.: DYJets_corr_NLO_2btag_down.SetBinContent(pt_bin,mass_bin,1.)
  DYJets_corr_NLO_2btag_down.Draw("COLZ")
  #plot.DrawCMSLogo(canv34, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv34, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv34, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv34.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag_down.pdf"%(channel,year))
  canv34.SaveAs("plots/%s_%s/DYJetscorr_NLO_2btag_down.png"%(channel,year))
  DYJets_corr_NLO_2btag_down.Write()
  canv35 = TCanvas("DYJetscorr_pt_NLO_2btag_down","DYJets Correction pt NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_pt_NLO_2btag_down = TH1D("DYJetscorr_pt_NLO_2btag_down","DYJets Correction pt NLO 2btag",11,np.array([0.,10.,20.,30.,40.,50.,60.,70.,90.,110.,150.,200.]))
  DYJets_corr_pt_NLO_2btag_down.Divide(hists_pt_2btag["dataMinusMC_down"],hists_pt_2btag["DYJets"])
  DYJets_corr_pt_NLO_2btag_down.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  DYJets_corr_pt_NLO_2btag_down.GetYaxis().SetTitle("weight")
  DYJets_corr_pt_NLO_2btag_down.Draw()
  #plot.DrawCMSLogo(canv35, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv35, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv35, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv35.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag_down.pdf"%(channel,year))
  canv35.SaveAs("plots/%s_%s/DYJetscorr_pt_NLO_2btag_down.png"%(channel,year))
  canv36 = TCanvas("DYJetscorr_mass_NLO_2btag_down","DYJets Correction mass NLO 2btag",600,400)
  gStyle.SetOptStat(0)
  DYJets_corr_mass_NLO_2btag_down = TH1D("DYJetscorr_mass_NLO_2btag_down","DYJets Correction mass NLO 2btag",8,np.array([50.,70.,80.,85.,90.,95.,100.,110.,130.]))
  DYJets_corr_mass_NLO_2btag_down.Divide(hists_mass_2btag["dataMinusMC_down"],hists_mass_2btag["DYJets"])
  DYJets_corr_mass_NLO_2btag_down.GetXaxis().SetTitle("dilepton mass (GeV)")
  DYJets_corr_mass_NLO_2btag_down.GetYaxis().SetTitle("weight")
  DYJets_corr_mass_NLO_2btag_down.Draw()
  #plot.DrawCMSLogo(canv36, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv36, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv36, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text+", tt xsec down")
  canv36.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag_down.pdf"%(channel,year))
  canv36.SaveAs("plots/%s_%s/DYJetscorr_mass_NLO_2btag_down.png"%(channel,year))

elif channel=="tt":
  channel_text = "e#mu CR"
  canv1 = TCanvas("TTcorr_pt","TT MC Correction",600,400)
  gStyle.SetOptStat(0)
  TT_corr = TH1D("TTcorr","",20,0.,200.)
  TT_corr.Divide(hists_pt["dataMinusMC"],hists_pt["TT"])
  TT_corr.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  TT_corr.GetYaxis().SetTitle("data/TT")
  TT_corr.Fit("pol0","Q")
  TT_corr.GetYaxis().SetRangeUser(0.89,1.025)
  TT_corr.Draw()
  #plot.DrawCMSLogo(canv1, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv1, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv1, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv1.SaveAs("plots/%s_%s/TTcorr_pt.pdf"%(channel,year))
  canv1.SaveAs("plots/%s_%s/TTcorr_pt.png"%(channel,year))
  canv1.SaveAs("plots/thesis/TTcorr_pt_%s_%s.pdf"%(channel,year))
  #fit_pt = TT_corr.GetFunction("pol0")
  #wt_tt_pt = fit_pt.GetParameter(0)
  TT_corr.Write()
  canv2 = TCanvas("TTcorr_mass","TT Correction mass",600,400)
  gStyle.SetOptStat(0)
  TT_mass_corr = TH1D("TTmasscorr","TT mass Correction",16,50.,130.)
  TT_mass_corr.Divide(hists_mass["dataMinusMC"],hists_mass["TT"])
  TT_mass_corr.GetXaxis().SetTitle("dilepton mass (GeV)")
  TT_mass_corr.GetYaxis().SetTitle("data/TT")
  TT_mass_corr.Fit("pol0","Q")
  #fit_mass = TT_mass_corr.GetFunction("pol0")
  #wt_tt_mass = fit_mass.GetParameter(0)
  TT_mass_corr.Write()
  TT_mass_corr.Draw()
  #plot.DrawCMSLogo(canv2, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv2, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv2, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv2.SaveAs("plots/%s_%s/TTcorr_mass.pdf"%(channel,year))
  canv2.SaveAs("plots/%s_%s/TTcorr_mass.png"%(channel,year))
  #####
  canv3 = TCanvas("TTcorr_pt_pol1","TT MC Correction",600,400)
  gStyle.SetOptStat(0)
  TT_corr_pol1 = TH1D("TTcorr_pol1","TT Correction",20,0.,200.)
  TT_corr_pol1.Divide(hists_pt["dataMinusMC"],hists_pt["TT"])
  TT_corr_pol1.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  TT_corr_pol1.GetYaxis().SetTitle("data/TT")
  TT_corr_pol1.Fit("pol1","Q")
  TT_corr_pol1.Draw()
  TT_corr_pol1.Write()
  #plot.DrawCMSLogo(canv3, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv3, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv3, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv3.SaveAs("plots/%s_%s/TTcorr_pt_pol1.pdf"%(channel,year))
  canv3.SaveAs("plots/%s_%s/TTcorr_pt_pol1.png"%(channel,year))
  canv4 = TCanvas("TTcorr_pt_pol2","TT MC Correction",600,400)
  gStyle.SetOptStat(0)
  TT_corr_pol2 = TH1D("TTcorr_pol2","TT Correction",20,0.,200.)
  TT_corr_pol2.Divide(hists_pt["dataMinusMC"],hists_pt["TT"])
  TT_corr_pol2.GetXaxis().SetTitle("dilepton p_{T} (GeV)")
  TT_corr_pol2.GetYaxis().SetTitle("data/TT")
  TT_corr_pol2.Fit("pol2","Q")
  TT_corr_pol2.Draw()
  TT_corr_pol2.Write()
  #plot.DrawCMSLogo(canv4, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv4, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv4, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv4.SaveAs("plots/%s_%s/TTcorr_pt_pol2.pdf"%(channel,year))
  canv4.SaveAs("plots/%s_%s/TTcorr_pt_pol2.png"%(channel,year))
  #####
elif channel=="mutau" or channel=="etau":
  if channel=="mutau": 
    channel_text = "#mu#tau_{h} CR"
  elif channel=="etau":
    channel_text = "e#tau_{h} CR"
  canv1 = TCanvas("Wcorr_pt","W MC Correction",600,400)
  gStyle.SetOptStat(0)
  binning = np.array([30.,40.,50.,60.,70.,80.,100.,130.])
  W_corr = TH1D("Wcorr","",7,binning)
  W_corr.Divide(hists_taupt["dataMinusMC"],hists_taupt["WJets"])
  W_corr.GetXaxis().SetTitle("#tau p_{T} (GeV)")
  W_corr.GetYaxis().SetTitle("data/WJets")
  if channel=="mutau":
    W_corr.GetYaxis().SetRangeUser(0.55,1.)
  else:
    W_corr.GetYaxis().SetRangeUser(0.52,1.15)
  W_corr.Fit("pol1","Q")
  W_corr.Draw()
  #plot.DrawCMSLogo(canv1, "CMS", "Internal", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawCMSLogo(canv1, "Private work", "(CMS data/simulation)", 10, 0.045, 0.05, 1.0, '', 0.8)
  plot.DrawTitle(canv1, titleright, 3, 0.2, 0.4)
  latex = TLatex()
  latex.SetNDC()
  latex.SetTextFont(42)
  latex.DrawLatex(0.15, 0.68, channel_text)
  canv1.SaveAs("plots/%s_%s/Wcorr_pt.pdf"%(channel,year))
  canv1.SaveAs("plots/%s_%s/Wcorr_pt.png"%(channel,year))
  canv1.SaveAs("plots/thesis/Wcorr_pt_%s_%s.pdf"%(channel,year))
  W_corr.Write()
  



outfile.Close()
print("Done")
