#python3 draw_fractions.py -i ff_mutau_UL2018.root
#python3 draw_fractions.py -i ff_etau_UL2018.root
#python3 ff_derive.py -i ff_mutau_UL2018.root
#python3 ff_derive.py -i ff_etau_UL2018.root
python3 makePlots.py -i ff_mutau_UL2018.root
python3 makePlots.py -i ff_etau_UL2018.root
#python3 ffvarcheck_derive.py -i ffvarcheck_mutau_UL2018.root
#python3 ffvarcheck_derive.py -i ffvarcheck_etau_UL2018.root
#python3 draw_fractions.py -i ff_mutau_UL2017.root
#python3 draw_fractions.py -i ff_etau_UL2017.root
#python3 ff_derive.py -i ff_mutau_UL2017.root
#python3 ff_derive.py -i ff_etau_UL2017.root
python3 makePlots.py -i ff_mutau_UL2017.root
python3 makePlots.py -i ff_etau_UL2017.root
#python3 ffvarcheck_derive.py -i ffvarcheck_mutau_UL2017.root
#python3 ffvarcheck_derive.py -i ffvarcheck_etau_UL2017.root
#python3 draw_fractions.py -i ff_mutau_UL2016.root
#python3 draw_fractions.py -i ff_etau_UL2016.root
#python3 ff_derive.py -i ff_mutau_UL2016.root
#python3 ff_derive.py -i ff_etau_UL2016.root
python3 makePlots.py -i ff_mutau_UL2016.root
python3 makePlots.py -i ff_etau_UL2016.root
#python3 ffvarcheck_derive.py -i ffvarcheck_mutau_UL2016.root
#python3 ffvarcheck_derive.py -i ffvarcheck_etau_UL2016.root
